export const GIFTED_TYPES = {
  GET_ALL_GIFTED: 'GET_ALL_GIFTED',
  GET_ALL_GIFTED_SUCCESS: 'GET_ALL_GIFTED_SUCCESS',
  GET_ALL_GIFTED_FAIL: 'GET_ALL_GIFTED_FAIL',

  INSERT_NEW_GIFTED: 'INSERT_NEW_GIFTED',
  INSERT_NEW_GIFTED_SUCCESS: 'INSERT_NEW_GIFTED_SUCCESS',
  INSERT_NEW_GIFTED_FAIL: 'INSERT_NEW_GIFTED_FAIL',
}

export const GIFT_LIST_TYPES = {
  GET_GIFT_LIST: 'GET_GIFT_LIST',
  GET_GIFT_LIST_SUCCESS: 'GET_GIFT_LIST_SUCCESS',
  GET_GIFT_LIST_FAIL: 'GET_GIFT_LIST_FAIL',
}